### ISSUE TITLE
meteor svelte project layout

### ISSUE THREAD

**Issue by dschulten** [klaussner/meteor-svelte#2]
I have just reworked a default meteor project with

client/main.html
client/HelloWorld.html

so that main.html contains the index.html content of the Svelte quickstart. I.e. my main.html looks as shown below:

```
<!doctype html>
<html>
<head>
    <title>My first Svelte app</title>
</head>
<body>
<main></main>
<script src='HelloWorld.js'></script>
<script>
    var app = new HelloWorld({
        target: document.querySelector( 'main' ),
        data: {
            name: 'world'
        }
    });
</script>
</body>
</html>
```

Meteor detects changes and attempts to run the svelte compiler, but I get this error:

_While processing files with klaussner:svelte (for target web.browser):
client/main.html:1:1: Expected valid tag name_

From my svelte experience, that means, the compiler tries to compile the main.html as a component. How should I lay out my meteor project so that the svelte compiler does not compile main.html, but only my components?

**Comment by klaussner** [comment]
The error is caused by the HTML parser not recognizing `<!doctype html>` when determining if the file is a Svelte component or not. But you don't need that line anyway because Meteor adds it automatically. The same applies to the `html` and `script` tags: instead of including `HelloWorld.js` and instantiating `HelloWorld` with `<script>` tags, just create a file `main.js` in the `client` directory that imports the component:

```js
import HelloWorld from '/imports/HelloWorld.html';

var app = new HelloWorld({
  target: document.querySelector('main'),
  data: {
    name: 'world'
  }
});

```

I've created a repo with an adapted version of the "Hello World" example from the Svelte Guide here: https://github.com/meteor-svelte/hello-world

**Comment by dschulten** [comment]
Thank you very much, the sample is running fine. What I find puzzling now is the fact that meteor by default pulls in *lots* of libraries and frameworks. One of my motivations to look into svelte is to build applications which do not do that. I tried with just meteor-base and klaussner:svelte, and I get more than 20 js script imports, among them underscore. That kind of defeats the purpose of svelte. I am totally new to meteor, just noting this.

**Comment by klaussner** [comment]
`underscore` is used in many places in the Meteor core and there have been discussions about removing this dependency or replacing it with `lodash`. But I don't think that it's likely to be removed in the near future. If you want to make your app payload smaller, you can fine-tune the dependecies a bit more because [`meteor-base`](https://github.com/meteor/meteor/blob/devel/packages/meteor-base/package.js) is just a meta package that includes other packages. For a minimal ES2015 app, you could use this list of packages:

```
meteor
webapp
standard-minifier-css
standard-minifier-js
ecmascript
klaussner:svelte
```

A production build with this configuration has a size of 45.8 KB (less than one third of minified React). However, you won't get any data loading functionality (i.e., Minimongo) or convenient features like hot code push. :smile:
